CREATE TABLE [dbo].StoreInventory
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[StoreId] BIGINT NOT NULL,
	[ProductId] BIGINT NOT NULL,
	CONSTRAINT [StoreFK] FOREIGN KEY (StoreId) REFERENCES Store(Id),
	CONSTRAINT [ProductFK] FOREIGN KEY (ProductId) REFERENCES Product(Id),
)
